# NumPy
**Num**erical **Py**thon

<img src="https://numpy.org/images/logo.svg" width="100" height="100"/>

[공식] (https://numpy.org/)


In [4]:
# numpy : 수치적 연산을 위해 최적화된 모듈
#  파이썬을 활용한 데이터 분석에서  가장 기본!
#  이 자체로도 많이 쓰이거니와, 앞으로 배울 pandas, 머신러닝 등 수많은 분야에서 기본적으로 사용하는 모듈
#  파이썬 개발자라면 꼭 익힐 필요 있다

# 수학수치 연산  (numerical python) / 합, 평균, 행렬연산 등..
# 추가적으로 scipy, statsmodel  같은 것들도 numpy 기반으로 구현됨.
# 상황에 따라, pandas 안써도 numpy 만으로도 가능.

# 기본 타입 : ndarray  (n-dimensional array) 다차원 배열 표현

# 파이썬에 list 가 있는데 굳이? 왜?  -

# numpy 를 사용하는 이유
# 1. 성능 : 성능적으로 훨~씬 빠름.
# 2. 메모리 : 훨씩 적은 메모리사용
# 3. 제공함수풍부 : 선형대수, 통계관련 여러 수치함수 제공
# 4. 수많은 모듈에서 numpy 함수명 과 기능을 그대로 사용.


In [5]:
import numpy as np

![aaa](https://media.licdn.com/dms/image/v2/C5112AQHb27esqXVOjg/article-cover_image-shrink_600_2000/article-cover_image-shrink_600_2000/0/1579022691240?e=2147483647&v=beta&t=olCUsjnPDaaRqRj2Da7S0Hl5kEJxu7v11H1GSir50mc)

**Scalar** : 0차원 array (단일값)

**Vector** : 1차원 array

**Matrix** : 2차원 array

**Tensor** : 3차원(이상) array

# 1차원 array (벡터) 생성

In [6]:
# np.array(iterable)

arr1 = np.array([1, 2, 3, 4, 5])
arr1  # __repr__

array([1, 2, 3, 4, 5])

In [7]:
print(arr1)  # __str__

[1 2 3 4 5]


In [8]:
type(arr1)

numpy.ndarray

In [9]:
# scalar (0차원 array)
np.array(10)

array(10)

In [10]:
[1, 2, 3.14, '김', True]   # list 는 원소타입이 가각 다를수 있다!

[1, 2, 3.14, '김', True]

In [11]:
# 그러나!  numpy array의 모든 원소는 '한가지 타입' 으로만 정의된다!

# shape, size, ndim, dtype 그리고 len()

In [12]:
arr1

array([1, 2, 3, 4, 5])

## shape
numpy에서는 해당 array의 크기를 알 수 있다.<br>
shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.<br>
위에서 arr1.shape의 결과는 (5,) 으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.
arr4.shape의 결과는 (4,3) 으로써, 2차원의 데이터이며 4 * 3 크기를 갖고 있는 array 이다.


In [13]:
arr1.shape

# (5,)  <- 숫자의 개수는 차원.
# 차원의 크기는 5

(5,)

## ndim  차원수

In [14]:
# 몇 차원 데이터인지?
arr1.ndim

# ndim 과 len(arr.shape) 은 같다!

1

In [15]:
len(arr1.shape)

1

## size : 데이터 개수

In [16]:
arr1.size

5

## len(array)
- array 는 iterable 하다!

In [17]:
len(arr1)

5

## dtype: data type

In [18]:
arr1.dtype

# dtype('int64')  정수 64bit (8byte)

dtype('int64')

In [19]:
arr2 = np.array([10, 3.14, 2, 0.12])
arr2

array([10.  ,  3.14,  2.  ,  0.12])

In [20]:
arr2.dtype

dtype('float64')

In [21]:
# numpy에서 사용되는 자료형은 아래와 같다. (자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

# 부호가 있는 정수 int(8, 16, 32, 64)
# 부호가 없는 정수 uint(8 ,16, 32, 64)
# 실수 float(16, 32, 64, 128)
# 복소수 complex(64, 128, 256)
# 불리언 bool
# 문자열 string_
# 파이썬 오프젝트 object
# 유니코드 unicode_

# 2차원 array 생성

In [22]:
# 2차원 array 생성
arr2 = np.array([[2, 3, 4], [1, 2, 3]])

arr2


array([[2, 3, 4],
       [1, 2, 3]])

In [23]:
arr2.shape

(2, 3)

In [24]:
arr2.ndim

2

In [25]:
# 1차원 배열의 원소는 스칼라값 (0차원)
# 🔹TODO

In [26]:
# 2차원 배열의 원소는 1차원 배열
len(arr2)

2

In [27]:
arr2.size

6

# 같은 값이라도 '차원' 이 다를 수 있다
'차원변환' 중요하다!

In [28]:
# scalar 0차원
arr = np.array(10)
arr

array(10)

In [29]:
# 1차원
arr1 = np.array([10])
arr1

array([10])

In [30]:
# 2차원
arr2 = np.array([[10]])
arr2

array([[10]])

# item()

In [31]:
# size가 1인 array의 데이터
arr.item()

10

In [32]:
arr1.item()

10

In [33]:
arr2.item()

10

# np.arange()
- array 생성
- range() 와 사용법 유사

In [34]:
# 0 부터 10 전까지  [0, 10)
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [37]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [38]:
np.arange(1, 10, dtype=np.int16)

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)

# astype(타입)
타입변환한 array 를 리턴 (원본 변화 없슴!)

In [39]:
d = np.arange(3, 10)
d   # dtype=int64 타입

array([3, 4, 5, 6, 7, 8, 9])

In [40]:
d.astype(np.float64)

array([3., 4., 5., 6., 7., 8., 9.])

In [41]:
# 원본은 변화 없다
d

array([3, 4, 5, 6, 7, 8, 9])

# reshape()
 - ndarray의 형태, 차원을 바꾸기 위해 사용
 - 머신러닝, 데이터 프로세싱에서 매우 자주 사용됨. (차원변환)

In [42]:
# (12,) -> (2, 6)
np.arange(12).reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [135]:
# size 안 맞으면 에러!

np.arange(12).reshape(2, 4)


ValueError: cannot reshape array of size 12 into shape (2,4)

In [134]:
np.arange(12).reshape(2, 2, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

# np.ones, np.zeros, np.eye, np.full

In [136]:
# np.ones(shape)  1 로 채워진 array 생성, dtype=float64(기본값) 으로 생성됨

np.ones(6)  # dtype=float64 로 만들어짐.


array([1., 1., 1., 1., 1., 1.])

In [137]:
np.ones((2, 3), dtype=np.int16)


array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [138]:
# np.zeros(shape)  0 으로 채워진 array 생성, dtype=float64(기본값) 으로 생성됨
np.zeros((3, 2, 5))


array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [139]:
# np.eye(N) 단위행렬, 주대각선만 1이고 나머지는 0 인 (N,N) array 생성

np.eye(5, dtype=np.int32)  # -> (5, 5) 단위 행렬


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [140]:
# np.full(shape, fill_value) 특정값으로 채워진 array 생성
np.full((2, 3), 10)


array([[10, 10, 10],
       [10, 10, 10]])

# np.random 서브모듈

In [141]:
# rand: 0부터 1사이의 균일 분포 [0, 1)  uniform distribution
# randn: 가우시안 표준 정규 분포 (평균0, 표준편차1 인 종모양 분포)  normal distribution
# randint: 균일 분포의 정수 난수
# seed: 램덤 시드값.  고정 난수값 생성

![](https://thebook.io/img/080263/218.jpg)

In [142]:
np.random.rand(10)


array([0.78786441, 0.76383076, 0.70297401, 0.83393912, 0.80197789,
       0.17902873, 0.46033005, 0.69687815, 0.87372662, 0.51323781])

In [143]:
np.random.rand(2, 3)

array([[0.23917082, 0.03684428, 0.13273989],
       [0.39575107, 0.72397414, 0.50666758]])

In [144]:
np.random.randn(5)

array([ 0.67122039,  1.8160225 , -1.52143777, -0.46294257, -0.65284096])

In [145]:
np.random.rand(3, 4, 2)

array([[[0.69938159, 0.94759455],
        [0.62309572, 0.32546768],
        [0.07769131, 0.54688348],
        [0.46653609, 0.76310058]],

       [[0.19396291, 0.47111394],
        [0.77246208, 0.59165399],
        [0.7682703 , 0.90985679],
        [0.87368137, 0.09973792]],

       [[0.69290895, 0.54885526],
        [0.37056867, 0.05497942],
        [0.80208799, 0.08611958],
        [0.41467625, 0.64034854]]])

In [146]:
# 0 ~ 4 사이의 정수 난수 [0, 5)
np.random.randint(5)

0

In [147]:
np.random.randint(1, 10)  #[1, 10]

6

In [148]:

np.random.randint(1, 100, (3, 5, 2))

array([[[78, 43],
        [83, 49],
        [16, 18],
        [99, 73],
        [86, 35]],

       [[25, 82],
        [61, 14],
        [ 1, 98],
        [86,  2],
        [35,  8]],

       [[26, 11],
        [58, 17],
        [18, 74],
        [71,  8],
        [ 4, 51]]])

In [149]:
# seed() : 난수를 예측가능하도록 만든다.  실행할때마다 동일한 난수가 발생되도록 함.
np.random.seed(0)
np.random.rand(4)


array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

In [150]:
np.random.seed(1)
np.random.rand(4)


array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])

In [151]:
#  비결정적 연산 (Non-Deterministic Operations)
#    같은 코드, 같은 입력을 줬는데도 결과가 매번 조금씩 달라지는 연산

#  결정적 연산 (Deterministic Operations)
#    같은 코드, 같은 입력, 같은 시드를 주면 결과가 동일한 연산

# 인덱싱 index
 - 파이썬 리스트와 동일한 개념으로 사용
 - tuple 을 사용하여 각 차원별 인덱스에 접근 가능
 - 인덱싱 할때마다 차원감소

In [152]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
x[0]


np.int64(0)

In [154]:
type(x[0])  # python int 타입 아니다!

numpy.int64

In [155]:
x[0].item()  # int값 꺼내기

0

In [156]:
int(x[0])

0

In [157]:
x[-1]

np.int64(9)

In [158]:
x[3] = 100   # array 는 mutable!
x

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9])

In [159]:
y = np.arange(10).reshape(2, 5)
y # 2차원

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [160]:
y[0]  # 1차원


array([0, 1, 2, 3, 4])

In [161]:
y[0][2]  # 0차원


np.int64(2)

In [162]:
# 콤마로 차원별 인덱싱 가능!  numpy 에선 후자의 방법을 추천!
y[0, 2]


np.int64(2)

## Advanced Indexing
- Integer array indexing

In [163]:
x = np.arange(100, 1000, 100)
x

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [164]:
x[0]  # 0차원 (차원 감소)

np.int64(100)

In [165]:
x[[0]]  # 1차원 (차원 감소 없다)


array([100])

In [166]:
x[[0, 1, 4, 3, 1, 1, 1, 4]]  # 원하는 것만, 원하는 만큼, 원한는 순서로 인덱싱 가능


array([100, 200, 500, 400, 200, 200, 200, 500])

# 슬라이싱 slice
 - 리스트, 문자열 slicing과 동일한 개념으로 사용
 - tuple 을 사용하여 각 차원 별로 슬라이싱 가능
 - 슬라이싱은 차원 변화 없다

In [167]:
x

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [168]:
x[1:7]  # 1차원 (차원변화 없다.)

array([200, 300, 400, 500, 600, 700])

In [169]:
x[1:]

array([200, 300, 400, 500, 600, 700, 800, 900])

In [170]:
x[:]

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [171]:
x[...]

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [172]:
x[::2]

array([100, 300, 500, 700, 900])

In [173]:
x[1::3]

array([200, 500, 800])

In [174]:
x[::-1]

array([900, 800, 700, 600, 500, 400, 300, 200, 100])

In [175]:
# list 의 경우 생각해보자
y = [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9],
     [10, 11, 12, 13, 14]]
y

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [176]:
y[0:1]  # 행 (axis=0) 에 대한 slicing

[[0, 1, 2, 3, 4]]

In [177]:
y[1:3]

[[5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [178]:
# 과연 아래와 같이 slicing 가능한가?
# [[1, 2, 3],
#  [6, 7, 8]]
y[:2]


[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]

In [179]:
y[:2][1:4]


[[5, 6, 7, 8, 9]]

In [180]:
# ↑ list 는 차원별 slicing 이 불가능하다!
# ↓ array 는 차원별 slicing 가능하다!

In [181]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [182]:
x[:2][1:4]


array([[5, 6, 7, 8, 9]])

In [183]:
# array 는 차원별 slicing 가능하다!
x[:2, 1:4]


array([[1, 2, 3],
       [6, 7, 8]])

In [184]:
x[2, 1:4]


array([11, 12, 13])

---
# shape (차원) 변경하기
**차원변환**은 데이터분석 과 인공지능에서 매우 빈번하게 발생되는 작업이니만큼 자유자재로 변환할수 있어야 하고, 머리속으로 내가 변환하는 데이터의 구조가 그려지도록 익숙해져야 합니다

사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨

## ravel(), np.ravel()
  - [ˈrævl]
  - 다차원배열을 1차원으로 변경 (흔히 '**펼친다**'라고 말함)
  - 'order' 파라미터
    - 'C' - row 우선 변경 ,   C style
    - 'F - column 우선 변경,   Fortran style
  - ravel() 은 np 안에 일반 함수로도 있고, 혹은 ndarray 의 멤버함수로서도 존재

## flatten()
 - 다차원 배열을 1차원으로 변경
 - ravel과의 차이점:
     - copy를 생성하여 변경함(즉 원본 데이터가 아닌 복사본을 반환)
     - ndarray 의 멤버함수로만 제공됨
 - 'order' 파라미터
   - 'C' - row 우선 변경
   - 'F - column 우선 변경

In [185]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [186]:
x.ravel()  # (3, 5) -> (15,)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [187]:
np.ravel(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [188]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [189]:
x.ravel(order='F')

array([ 0,  5, 10,  1,  6, 11,  2,  7, 12,  3,  8, 13,  4,  9, 14])

## reshape 함수
 - array의 shape을 다른 차원으로 변경
 - 주의할점은 reshape한 후의 결과의 전체 원소 개수(size)와 이전 개수가 같아야 가능
 - 사용 예) 이미지 데이터 벡터화 - 이미지는 기본적으로 2차원 혹은 3차원(RGB)이나 트레이닝을 위해 1차원으로 변경하여 사용 됨
 - **-1** 값을 주어 나머지 차원을 유추하게 할수 있다

In [190]:
x2 = np.arange(36)
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [191]:
x2.reshape(6, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [192]:
# -1 의 차원 크기가 유추되어 reshape 된다  => (6, 6)
x2.reshape(6, -1)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [193]:
x2.reshape(6, -1, 2)  # (6, ? ,2)


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [194]:
x2.reshape(-1, 5, 3)

ValueError: cannot reshape array of size 36 into shape (5,3)

In [195]:
x2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [196]:
x2.shape = 3, -1, 4  # 직접 shape값 입력 -> 원본 변화

x2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [197]:
# 도전]
# 다음 주어진 array 에서 첫번째 col 만 추출하려면?

# array([[ 10,  20,  30,  40],
#        [  1,   2,   3,   4],
#        [100, 200, 300, 400]])

""" 결과
array([ 10,   1, 100])
"""

arr31 = np.array([[ 10,  20,  30,  40],
                  [  1,   2,   3,   4],
                  [100, 200, 300, 400]])
arr31



array([[ 10,  20,  30,  40],
       [  1,   2,   3,   4],
       [100, 200, 300, 400]])

In [198]:
arr31[:, 0]

array([ 10,   1, 100])

## 차원 확장 / 제거

- 차원 확장/제거 하는 동작도 머신러닝에서 많이 사용된다.
- **reshape()** 로 차원 변환(확장/제거) 자유롭게 가능

### 차원 확장 : np.expand_dims()
- axis= 로 지정된 '차원을 추가'한다.


### 차원 자동 제거 : squeeze, np.squeeze()

- 차원 중 사이즈가 1인 것을 찾아 스칼라값으로 바꿔 해당 '차원을 제거'한다.

In [199]:
x3 = np.arange(6)  # (6,)
x3

array([0, 1, 2, 3, 4, 5])

In [200]:
# (6,) => (6, 1) 로 차원 확장
x3 = x3.reshape(6, 1)
x3


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [201]:
x3 = x3.reshape(6, 1, 1)
x3


array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]]])

In [202]:
# 1차원으로 축소 (차원 제거)
x3.reshape(6)


array([0, 1, 2, 3, 4, 5])

In [203]:
# squeeze() 사용. 차원크기가 1인 차원을 제거  (6, 1, 1) => (6,)
x3.shape
x3.squeeze()

array([0, 1, 2, 3, 4, 5])

In [204]:
x4 = np.arange(6).reshape((2, 1, 3, 1))
x4

array([[[[0],
         [1],
         [2]]],


       [[[3],
         [4],
         [5]]]])

In [205]:
# (2, 1, 3, 1) => (2, 3)
x4.squeeze()

array([[0, 1, 2],
       [3, 4, 5]])

In [206]:
x5 = np.arange(3)  # (3,)
x5

array([0, 1, 2])

In [207]:
# expand_dims 사용: 0번째 차원축(axis) 에 새로운 차원 추가(삽입)
y5 = np.expand_dims(x5, axis=0)
print(y5.shape)  # (3,) -> (1, 3)
y5


(1, 3)


array([[0, 1, 2]])

In [208]:
x6 = np.arange(4).reshape(2, 2)
x6

array([[0, 1],
       [2, 3]])

In [209]:
# 마지막에 차원축 추가
# (2, 2) => (2, 2, 1)

y6 = np.expand_dims(x6, axis=-1)
print(y6.shape)
y6



(2, 2, 1)


array([[[0],
        [1]],

       [[2],
        [3]]])

In [210]:
# axis 0 과 axis -1 에 새로운 차원 추가
y7 = np.expand_dims(x6, axis=(0, -1))
print(y7.shape)
y7



(1, 2, 2, 1)


array([[[[0],
         [1]],

        [[2],
         [3]]]])

In [211]:
x8 = np.array([2, 0, 1, 8])  # (4,)
x8

array([2, 0, 1, 8])

In [212]:
# np.newaxis 사용
y8 = x8[np.newaxis, :]  # (4,) -> (1, 4)
print(y8.shape)
y8


(1, 4)


array([[2, 0, 1, 8]])

In [213]:
# ↑ 1차원 벡터를 row vector 로 변환한다 라고도 함.

In [214]:
# np.newaxis 사용. (4,) => (4, 1)
a2 = x8[:, np.newaxis]
print(a2.shape)
a2


(4, 1)


array([[2],
       [0],
       [1],
       [8]])

In [215]:
# ↑ 1차원 벡터를 column vector 로 변환한다 라고도 함.

# transpose, T,  swapaxes
전치행렬 (transpose matrix) , 차원 축 바꾸기

![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FbtmNz3%2FbtqDk6Xy5nh%2FD7U80E2R3fnahK00cijoY1%2Fimg.png)

In [216]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [217]:
# transpose. (3, 5) => (5, 3)
np.transpose(a)


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [218]:
# .T
a.T


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [219]:
# swapaxes() 사용. axis 0 과 axis 1 을 바꾸기
# (3, 5) => (5, 3)
np.swapaxes(a, 0, 1)


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [220]:
b = np.arange(24).reshape(2, 3, 4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [221]:
b.T   # 2 x 3 x 4 => 4 x 3 x 2

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [222]:
b.T.shape

(4, 3, 2)

In [223]:
# 바꾸고 싶은 axis 차원축의 순서 지정 가능.
np.transpose(b, (2, 1, 0))  # 2 x 3 x 4 => 4 x 3 x 2

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

# 🟦 기본연산, 기본함수

In [224]:
np.random.seed(42)
x = np.arange(15).reshape(3, 5)
y = np.arange(0, 150, 10).reshape(3, 5)
y2 = np.random.rand(15).reshape(3, 5)
y3 = np.arange(15).reshape(5, 3)

In [225]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [226]:
y

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140]])

In [227]:
y2

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

In [228]:
y3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## array 간 연산

In [229]:
# 리스트의 경우는 어떠했나?
a = [10, 20, 30, 40]
b = 2
c = [100, 200, 300, 400]

In [230]:
a * 2

[10, 20, 30, 40, 10, 20, 30, 40]

In [231]:
# a + b  # 에러


In [232]:
a + c # list + list

[10, 20, 30, 40, 100, 200, 300, 400]

In [233]:
# array 연산은 리스트와 다르다!
# 기본적으로 '원소' 끼리 연산 (element-wise operation) 수행

In [234]:
x + y


array([[  0,  11,  22,  33,  44],
       [ 55,  66,  77,  88,  99],
       [110, 121, 132, 143, 154]])

In [235]:
x - y


array([[   0,   -9,  -18,  -27,  -36],
       [ -45,  -54,  -63,  -72,  -81],
       [ -90,  -99, -108, -117, -126]])

In [236]:
# array 와 스칼라 값 연산 가능
x + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [237]:
# 단일값만 갖고 있는 객체와는 shape 관계없이, scalar 연산 수행
x + [10]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [238]:
x + [[10]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## axis (차원축)

In [239]:
# numpy 의 많은 함수들은 axis=  파라미터를 갖고 있습니다.
# axis (축) 은 각 '차원' 을 의미합니다.
# 1차원 array 라면  각 차원에 대한 axis 값은 0  <- 1개 입니다.
# 2차원 array 라면  각 차원에 대한 axis 값은 0, 1  <- 2개 입니다.
# 3차원 array 라면  각 차원에 대한 axis 값은 0, 1, 2  <- 3개 입니다.

# axis= 값을 명시하면 그 함수의 연산 은 해당 axis(축) 에 '따라서' 연산을 수행함

# 과연 '따라서' 의 의미가 무엇인지 실습을 통해 이해해봅시다

In [240]:
x1 = np.arange(15)
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [241]:
np.sum(x1)


np.int64(105)

In [242]:
np.sum?

In [243]:
np.sum(x1, axis=None)

np.int64(105)

In [244]:
x2 = x1.reshape(3, 5)
x2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [245]:
x2.shape

# (행, 열)
# (axis 0, axis 1)

(3, 5)

In [246]:
np.sum(x2)  # axis=None

np.int64(105)

In [247]:
np.sum(x2, axis=0)  # (3, 5) => (5,)

# 15 = 0 + 5 + 10
#     [0,0] + [1,0] + [2, 0]


array([15, 18, 21, 24, 27])

In [248]:
np.sum(x2, axis=1)  # (3, 5) => (3,)

array([10, 35, 60])

In [249]:
np.sum(x2, axis=-1)

array([10, 35, 60])

In [250]:
y

array([[  0,  10,  20,  30,  40],
       [ 50,  60,  70,  80,  90],
       [100, 110, 120, 130, 140]])

In [251]:
# max() 최댓값
np.max(y)


np.int64(140)

In [252]:
# argmax() 최댓값의 index
np.argmax(y)


np.int64(14)

In [253]:
np.max(y, axis=0)

array([100, 110, 120, 130, 140])

In [254]:
np.argmax(y, axis=0)

array([2, 2, 2, 2, 2])

# NaN (Not a Number)
- `NaN`은 정의되지 않거나 표현할 수 없는 **수치 결과**를 의미
- Numpy 에선 보통 `np.nan` 으로 NaN 표현

In [108]:
# NaN (Not a Number : 숫자이어야 하는데 숫자가 아닌 값, 숫자로 표현할수 없는 값)
# 실무 데이터를 다루다 보면 NaN 을 엄청나게 자주 만나게 된다.
#    원본데이터의 '누락' 이라든지, DBMS 상의 null 값이라든지 등등. 여러가지 이슈로 NaN 값 발생
#    ★그래서 데이터 분석시 NaN 값을 제거 하든지 혹은 치환 하든지.. 해서 처리할줄 알아야 한다


In [255]:
np.nan


nan

## isnan : nan 판별

In [256]:
np.isnan(100)


np.False_

In [257]:
np.isnan(np.nan)

np.True_

In [258]:
import math
math.isnan(np.nan)

True

## nan 과의 연산

In [259]:
# 기본적인 수치 연산에서 NaN이 하나라도 있으면 결과가 NaN
np.nan + 10


nan

In [260]:
arr = np.array([10, 20, np.nan])
arr

array([10., 20., nan])

In [261]:
np.sum(arr)  # nan  (※ 나중에 pandas 에서는 이 결과가 다르다!)


np.float64(nan)

# Broadcasting
#### 브로드캐스팅
  - (기본적으로는) Shape이 같은 두 ndarray에 대한 연산은 각 원소별로 진행
  - **다른 Shape을 갖는 array 간 연산** 의 경우 브로드 캐스팅(Shape을 맞춤) 후 진행
    
    
![](https://numpy.org/doc/stable/_images/broadcasting_1.png)

In [262]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [263]:
np.random.seed(42)
y = np.random.rand(15).reshape(3, 5)
y

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497]])

In [264]:
x + y

array([[ 0.37454012,  1.95071431,  2.73199394,  3.59865848,  4.15601864],
       [ 5.15599452,  6.05808361,  7.86617615,  8.60111501,  9.70807258],
       [10.02058449, 11.96990985, 12.83244264, 13.21233911, 14.18182497]])

In [265]:
a = np.arange(12).reshape(4, 3)
b = np.arange(100, 103)

In [118]:
a   # (4, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [119]:
b  # (3,)

array([100, 101, 102])

In [266]:
# 다른 shape 와의 덧셈 연산이 된다!
a + b


array([[100, 102, 104],
       [103, 105, 107],
       [106, 108, 110],
       [109, 111, 113]])

In [267]:
# broadcatding 의 강점!
#   shape 가 다른 데이터 까지의 연산을 '특별한 처리' 없이도 연산이 가능케 함

### 브로드캐스팅 Rule
 - [Rule 공식문서](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html#general-broadcasting-rules)
 - 뒷 차원에서 부터 비교하여 **①Shape이 같거나**, **②차원 중 값이 1이 존재**하면 broadcasting 가능
 - 결과 차원은 둘중 큰 size 의 차원으로 **확장** 된다



![브로드캐스팅 예](https://www.tutorialspoint.com/numpy/images/array.jpg)
    - 출처: https://www.tutorialspoint.com/numpy/images/array.jpg


In [ ]:
''' 브로드캐스팅 가용한 경우
    A     : 256 x 256 x 3
    B     :             3
    Result: 256 x 256 x 3

    A     : 8 x 1 x 6 x 1
    B     :     7 x 1 x 5
    Result: 8 x 7 x 6 x 5
'''

''' 브로드캐스팅 불가능한 경우
    A     : 3
    B     : 4

    A     :     2 x 1
    B     : 8 x 4 x 3
'''
None



In [272]:
a = np.full(4, 100)
a

array([100, 100, 100, 100])

In [273]:
a + 1

array([101, 101, 101, 101])

In [274]:
a + [1]

array([101, 101, 101, 101])

In [275]:
a + [[1]]

array([[101, 101, 101, 101]])

In [276]:
a = np.arange(12).reshape(4, 3)
c = np.arange(1000, 1004)

print(a.shape, c.shape)

(4, 3) (4,)


In [277]:
a + c

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [280]:
arr31 = np.arange(1, 25).reshape(2, 4, 3)
arr32 = np.array([10, 20]).reshape(2, 1, 1)

In [281]:
arr31

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [282]:
arr32

array([[[10]],

       [[20]]])

In [283]:
arr31 + arr32

array([[[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19],
        [20, 21, 22]],

       [[33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [284]:
# 도전!
arr21 = np.arange(10, 70, 10).reshape(2, 3)
arr23 = np.array([1, 2])


In [285]:
arr21

array([[10, 20, 30],
       [40, 50, 60]])

In [297]:
arr23.shape

(2,)

In [287]:
arr21 + arr23

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [288]:
# 과연 아래의 결과를 만들수 있을까?
""" 원하는 결과
array([[11, 22, 31],
       [42, 51, 62]])
"""
None


In [308]:
(arr21.reshape(-1, 2) + arr23).reshape(2, 3)

array([[11, 22, 31],
       [42, 51, 62]])

# 🟦Boolean Indexing

In [121]:
# 'Boolean indexing ' !
# array 인덱싱 시, bool 리스트(aka. mask)를 전달하여 True인 경우만 필터링

# for 사용하지 않고도 array 에서 '조건'에 맞는 데이터만 추출 하는 기능

# 머신러닝 등에 있어서도 많이 사용



In [309]:
# 브로드캐스팅을 활용하여 array로 부터 bool list 얻기
#  - 예) 짝수인 경우만 찾아보기

np.random.seed(41)
x = np.random.randint(1, 100, size=10)
x

array([65, 36, 13, 99, 81, 66, 90, 24, 86, 27])

In [310]:
x % 2


array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1])

In [311]:
even_mask = x % 2 == 0
even_mask


array([False,  True, False, False, False,  True,  True,  True,  True,
       False])

In [312]:
# 위와 같이 bool 값으로 이루어진 array 를 Mask 라고도 한다
# 위 결과, mask 를 변수에 담아 보겠습니다

# boolean mask 로 인덱싱!
x[even_mask]


array([36, 66, 90, 24, 86])

In [313]:
# list 나 tuple 같은 iterable 도 bool mask 로 사용 가능.

x[[False,  True, False, False, False,  True,  True,  True,  True, False]]


array([36, 66, 90, 24, 86])

In [314]:
x[x % 2 == 0]

array([36, 66, 90, 24, 86])

In [315]:
x[x > 30]

array([65, 36, 99, 81, 66, 90, 86])

## 다중조건 사용하기
 - 파이썬 논리 연산자인 and, or, not 키워드는 사용 불가
 - & ← AND
 - | ← OR

In [126]:
# ↓짝수이면서 30보다 작은 숫자들은?

In [318]:
x[(x % 2 == 0) & (x < 30)]


array([24])

In [319]:
# 30 보다 작은값 혹은 50보다 큰값들
x[(x < 30) | (x > 50)]


array([65, 13, 99, 81, 66, 90, 24, 86, 27])

## astype() 으로 변환

In [320]:
# 기억하시죠?
True, int(True), False, int(False)

(True, 1, False, 0)

In [321]:
True + True

2

In [322]:
x > 50

array([ True, False, False,  True,  True,  True,  True, False,  True,
       False])

In [323]:
(x > 50).astype(int)

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [324]:
(x > 50).astype('int')

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 0])

In [326]:
(x > 50).astype(np.int32)

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 0], dtype=int32)

In [327]:
# x 에서 50보다 큰 숫자들의 개수는?
np.sum(x > 50)   # True 는 1, False 는 0 으로 sum

np.int64(6)

## 도전!  서울시 5월 일자별 평균기온

In [328]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6,
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9,
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5,
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

"""

도전]
Q1] 평균기온이 25도를 넘는 날의 수는?  => 21일
Q2] 평균기온이 25도를 넘는 날의 평균기온은? => 26.8도
"""
None

In [335]:
np.sum(temp > 25.0).item()

21

In [336]:
np.mean(temp[temp > 25.0]).item()

26.857142857142858

In [133]:
# ↑ for, while, if 등의 명시적인 제어문 사용하지 않고도
# numpy 만으로도 위 동작들 구현 가능.