# Pandas
panel data and analysis<br>
공식: https://pandas.pydata.org<br>
![](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2Fzy1Or%2FbtqM39h0uLB%2FfHnntePsHiwAIFStdqGsLk%2Fimg.png)

In [ ]:
# Pandas : 데이터 분석 라이브러리
# 행(row), 열(column) 형태의 '정형 데이터' 객체를 다룸
#  2차원 데이터
#  엑셀의 시트, RDB 의 테이블과 같은 형태

# 대표적인 객체는
#  DataFrame 과 Series

# Series
  - pandas의 기본 객체 중 하나
  - numpy의 ndarray를 기반으로 **인덱싱 기능**이 추가된 **1차원 배열**을 나타냄 (index x value 의 형태)
  - index를 지정하지 않을 시, 기본적으로 ndarray와 같이 0-based 인덱스 생성, 지정할 경우 명시적으로 지정된 index를 사용
  - **같은 타입**의 0개 이상의 데이터를 가질 수 있음

In [1]:
import numpy as np
import pandas as pd

# Series 생성

In [2]:
s1 = pd.Series([10, 20, 30])
s1

,0
0,10
1,20
2,30


In [ ]:
# ↑ 왼쪽이 index, 오른쪽이 value (값),  dtype : 데이터 타입
# 데이터로만 생성하게 되면,  index 는 0-base 인덱스로 생성됨

In [3]:
print(s1)

0    10
1    20
2    30
dtype: int64


## .values  .index  .dtype

In [4]:
s1.values

array([10, 20, 30])

In [5]:
s1.index

RangeIndex(start=0, stop=3, step=1)

In [6]:
s1.dtype

dtype('int64')

In [7]:
# indexing
s1[0]

np.int64(10)

In [8]:
s1[5]

KeyError: 5

## data=. index= 명시하여 Series 생성

In [10]:
pd.Series(data=[1, 2, 3], index=[100, 200, 300])


,0
100,1
200,2
300,3


In [11]:
# index 는 굳이 정수일 필요 없다!
s5 = pd.Series([1, 2, 3], ['희준', '정준', '영진'])
s5

,0
희준,1
정준,2
영진,3


In [12]:
# 인덱싱
s5['희준']

np.int64(1)

In [13]:
# index 중복 허용된다!!  (array 와는 다르다!)
s6 = pd.Series([1, 2, 3], ['john', 'john', 'charlie'])
s6

,0
john,1
john,2
charlie,3


In [14]:
# 중복 indexing 결과 Series!!
s6['john']

,0
john,1
john,2


## dict 로 생성

In [15]:
# dict 로 Series 생성
sdata = {'김철수': 35000, '이상현': 67000, '최종수': 12000, '박진관': 4000}
pd.Series(sdata)

# dict 의
#   key -> index,
#   value -> value,

,0
김철수,35000
이상현,67000
최종수,12000
박진관,4000


# indexing

In [16]:
s7 = pd.Series(data=np.arange(5), index=np.arange(100, 105), dtype=np.int16)
s7

,0
100,0
101,1
102,2
103,3
104,4


In [17]:
s7.index

Index([100, 101, 102, 103, 104], dtype='int64')

In [18]:
s7.index.values

array([100, 101, 102, 103, 104])

In [19]:
s7[102].item()  # 결과: scalar value

2

In [20]:
s7[[102, 104]]  # 결과: Series

,0
102,2


In [21]:
s7[[104, 101, 104, 104, 102]]

,0
104,4
101,1
104,4
104,4
102,2


In [22]:
# value 변경 가능
s7[104] = 70
s7

,0
100,0
101,1
102,2
103,3
104,70


In [23]:
# keyError
s7[105]

KeyError: 105

In [25]:
# 기존에 없던 인덱스에 값 대입 -> 새로 생긴다!  (numpy 와 다르다!)
s7[105] = 90
s7


,0
100,0
101,1
102,2
103,3
104,70
105,90


# **Series ndim, shape, size, len, unique, count, value_counts 함수**
 - size : 개수 반환
 - shape : 튜플형태로 shape반환
 - unique: 유일한 값만 ndarray로 반환
 - count : NaN을 제외한 개수를 반환
 - mean: NaN을 제외한 평균
 - value_counts: NaN을 제외하고 각 값들의 빈도를 반환

In [26]:
# ※np.NaN 은 numpy 2.0 에서 없어짐
s1 = pd.Series([1, 1, 2, 1, 2, 2, 2, 1, 1, 3, 3, 4, 5, 5, 7, np.nan])
s1



,0
0,1.0
1,1.0
2,2.0
3,1.0
4,2.0
5,2.0
6,2.0
7,1.0
8,1.0
9,3.0


In [27]:
s1.ndim

1

In [28]:
s1.shape

(16,)

In [29]:
s1.size

16

In [30]:
len(s1)

16

In [32]:
s1.unique()  # -> array

array([ 1.,  2.,  3.,  4.,  5.,  7., nan])

In [ ]:
# nan 값의 연산
#  - 집계연산의 경우 nan 값은 제외되어 연산된다 (numpy 와 다른점!)
#  - count, mean, max, min ...

In [33]:
s1.count()  # 데이터가 있는 것만 count 한다! NaN 은 제외된다!

np.int64(15)

In [34]:
# numpy 의 경우 array 원소 중에 NaN 이 있으면 연산 불가 (즉 NaN 이 나옴)
a1 = np.array([2, 2, 2, 2, np.nan])
a1.mean() # nan 이 나온다...

np.float64(nan)

In [35]:
# 반면! Series 는 NaN 원소 무시하고 평균값 산출
pd.Series(a1).mean()


np.float64(2.0)

In [36]:
# value_counts()  고유한 값들의 개수
s1.value_counts()

,count
1.0,5
2.0,4
3.0,2
5.0,2
4.0,1
7.0,1


# Series 연산
- index 기준으로 연산

In [ ]:
# numpy 와 마찬가지로
# Series 도 Series 끼리 연산 가능.
#  기억할 포인트는 '같은 인덱스' 기준으로 연산한다는 겁니다
#  이 특징은 DataFrame 에서도 동일하게 적용됩니다.

In [37]:
s1 = pd.Series([1, 2, 3, 4], ['a', 'b', 'c', 'd'])
s2 = pd.Series([6, 3, 2, 1], ['d', 'c', 'b', 'a'])  # 인덱스 순서 다르다

In [38]:
s1

,0
a,1
b,2
c,3
d,4


In [39]:
s2

,0
d,6
c,3
b,2
a,1


In [40]:
s1 + s2

,0
a,2
b,4
c,6
d,10


# 산술연산
 - Series의 경우에도 **스칼라와의 연산** 각 원소별로 스칼라와의 연산이 적용
 - Series와의 연산은 각 인덱스에 맞는 값끼리 연산이 적용
   - 이때, 인덱스의 pair가 맞지 않으면, 결과는 NaN

In [41]:
s1 ** 2

,0
a,1
b,4
c,9
d,16


In [42]:
s1 ** s2  # Series 는 동일 인덱스끼리 연산

,0
a,1
b,4
c,27
d,4096


## **index pair가 맞지 않는 경우**
 - 해당 index에 대해선 NaN 값 생성

In [44]:
s1['k'] = 7
s2['e'] = 9

In [45]:
s1

,0
a,1
b,2
c,3
d,4
k,7


In [46]:
s2

,0
d,6
c,3
b,2
a,1
e,9


 # **Boolean selection**
  - boolean Series가 []와 함께 사용되면 True 값에 해당하는 값만 새로 반환되는 Series객체에 포함됨
  - 다중조건의 경우, &(and), |(or)를 사용하여 연결 가능

In [47]:
s = pd.Series(np.arange(10), np.arange(10) + 1)
s

,0
1,0
2,1
3,2
4,3
5,4
6,5
7,6
8,7
9,8
10,9


In [49]:
s > 5  # 결과는 boolean Series

,0
1,False
2,False
3,False
4,False
5,False
6,False
7,True
8,True
9,True
10,True


In [50]:
# 5보다 큰 value 들만 골라낸 Series
s[s > 5]


,0
7,6
8,7
9,8
10,9


In [48]:
# 짝수 value 들만 골라낸 Series
s[s % 2 == 0]


,0
1,0
3,2
5,4
7,6
9,8


# Series 값 삭제: drop()

In [51]:
s = pd.Series(np.arange(100, 105), ['a', 'b', 'c', 'd', 'e'])
s

,0
a,100
b,101
c,102
d,103
e,104


In [52]:
s['a'] = 200
s

,0
a,200
b,101
c,102
d,103
e,104


In [53]:
s['k'] = 300
s

,0
a,200
b,101
c,102
d,103
e,104
k,300


In [54]:
# 특정 index 삭제. 원본 변화 없다!
s.drop('k')


,0
a,200
b,101
c,102
d,103
e,104


In [55]:
 # 원본 변화 없슴 확인!
s

,0
a,200
b,101
c,102
d,103
e,104
k,300


## inplace= 원본변경

In [ ]:
# ★중요★
# drop() 함수는 drop 한'결과' 를 새로 만들어서 리턴한거고
# 원본 데이터 s 는 '변경'하지 않습니다

# numpy , pandas, 그밖의 수많은 데이터 관련 모듈들 에서의
# 대부분의 객체 함수들은 호출한 원본 객체를 '변경'하진 않고
# 원본의 '사본'을 만든뒤 '사본' 에 연산수행하여 그 '사본' 을 리턴하도록 동작 한다
# (함수마다 조금씩 다르긴 하다)

# 그러나!
# inplace=True 파라미터를 주면 '사본' 을 만들지 않고 '원본'을 변화시키도록 동작한다


In [56]:
s.drop('k', inplace=True)  # 이 경우 리턴값 없다! None (원본 변화 발생!)

In [57]:
s  # 변경된 사실 확인

,0
a,200
b,101
c,102
d,103
e,104


# Multi level index

In [58]:
s3 = pd.Series([1, 2, 3, 4, 5, 6], ['a', 'a', 'b', 'b', 'c', 'c'])
s3

,0
a,1
a,2
b,3
b,4
c,5
c,6


In [59]:
s3.index

Index(['a', 'a', 'b', 'b', 'c', 'c'], dtype='object')

In [ ]:
# ↑ 단일 level index 다!

In [61]:
# multi-level index 를 가진 Series

s4 = pd.Series(
    np.arange(100, 106),

    index = [
        ['a', 'a', 'b', 'b', 'c', 'c'],  # <- level 0 index
        [ 1,   2,   1,   2,   1,   2 ],  # <- level 1 index
    ],

)

s4


a  1    100
   2    101
b  1    102
   2    103
c  1    104
   2    105
dtype: int64

In [62]:
s4.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [63]:
# tuple 인덱싱으로 value 접근
s4['a', 1]


np.int64(100)

In [64]:
s4['a']  # 결과는 level 한 개 짜리 Series


,0
1,100
2,101


In [ ]:
# ↑
# s4: 2-level index
# s4['a'] : 1-level index

In [66]:
s4['a'][1]  # 비 추천 -> s4['a', 1] 이 방식을 권장


np.int64(100)

In [67]:
s4[['a']]


a  1    100
   2    101
dtype: int64

## xs() 를 사용한 인덱스
cross-section

In [68]:
s4.xs('a')  # level 0 인덱싱  <= s4['a'] 와 결과 동일

,0
1,100
2,101


In [69]:
s4.xs(('a', 1))  # () 괄호 꼭 필요!   # s4['a', 1] 과 동일

np.int64(100)

In [70]:
s4

a  1    100
   2    101
b  1    102
   2    103
c  1    104
   2    105
dtype: int64

In [72]:
# s4.xs(2)  # KeyError - level 0에는 2라는 index없다
s4.xs(2, level=1)


,0
a,101
b,103
c,105


In [73]:
s4.xs((2, 'b'))


KeyError: (2, 'b')

In [74]:
s4.xs((2, 'b'), level=(1, 0))


,,0
b,2,103


# apply() 함수
- Series각 value 원소 에 함수를 적용(apply)할 때 사용.
- 일종의 원소별(element-wise) 변환 역할

```python
Series.apply(func, convert_dtype=True, args=(), **kwargs)
```


In [79]:
s = pd.Series([1, 2, 3, 4, 5])

# 각 원소에 제곱 적용
result = s.apply(lambda x: x ** 2)
result

,0
0,1
1,4
2,9
3,16
4,25


In [81]:
# 사용자 정의함수 적용
def custom_func(x):
    return f"Value: {x}"

result = s.apply(custom_func)
result

,0
0,Value: 1
1,Value: 2
2,Value: 3
3,Value: 4
4,Value: 5


In [83]:
# 추가인자 전달
def multiply(x, factor):
    return x * factor

result = s.apply(multiply, args=(10,))
print(result)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [85]:
# 문자열 처리
s2 = pd.Series(["  apple ", "banana", " Cherry "])

# strip + 소문자 변환
result = s2.apply(lambda x: x.strip().lower())
print(result)

0     apple
1    banana
2    cherry
dtype: object
